# Generated by Django 5.0.2 on 2024-06-28 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_room_participants'),
        ('base', '0003_user_avatar'),
    ]

    operations = [
    ]
